# Import Libraries

In [1]:
import pandas as pd
import numpy as np

# Load Dataset

In [2]:
data = pd.read_csv('dataset.csv')

# Basic info

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              26 non-null     int64
 1   EstimatedSalary  26 non-null     int64
 2   Purchased        26 non-null     int64
dtypes: int64(3)
memory usage: 756.0 bytes


In [4]:
data.head()

,Age,EstimatedSalary,Purchased
0,19,19000,0
1,35,20000,0
2,26,43000,0
3,27,57000,0
4,19,76000,0


# Seprate Feature and label

In [5]:
features = data.iloc[:,[0,1]].values
label = data.iloc[:,2].values

# Feature Selection

In [6]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

algo = LogisticRegression()

In [7]:
rfe = RFE(estimator=algo)

rfe.fit(features,label)


,estimator,LogisticRegression()
,n_features_to_select,None
,step,1
,verbose,0
,importance_getter,'auto'
,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1


In [8]:
rfe.ranking_

array([1, 2])

# Model Building and Metrics Evaluation

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [10]:
for rs in range(1,101):
    x_train,x_test,y_train,y_test = train_test_split(features,label,test_size=0.2,random_state=rs)
    
    for k in range(1,11):
        model = KNeighborsClassifier(n_neighbors=k)
    
        model.fit(x_train,y_train)
    
        trainScore = model.score(x_train,y_train)
        testScore = model.score(x_test,y_test)
        
        if testScore >= 0.8:
            print(f"Test Score {testScore} and Train Score {trainScore} , rs {rs} , k {k}")

Test Score 1.0 and Train Score 1.0 , rs 1 , k 1
Test Score 0.8333333333333334 and Train Score 1.0 , rs 2 , k 1
Test Score 0.8333333333333334 and Train Score 0.9 , rs 2 , k 3
Test Score 0.8333333333333334 and Train Score 0.85 , rs 2 , k 4
Test Score 0.8333333333333334 and Train Score 0.8 , rs 2 , k 5
Test Score 0.8333333333333334 and Train Score 0.85 , rs 2 , k 6
Test Score 0.8333333333333334 and Train Score 0.85 , rs 2 , k 7
Test Score 0.8333333333333334 and Train Score 0.9 , rs 2 , k 8
Test Score 0.8333333333333334 and Train Score 0.85 , rs 2 , k 9
Test Score 0.8333333333333334 and Train Score 0.8 , rs 2 , k 10
Test Score 1.0 and Train Score 1.0 , rs 3 , k 1
Test Score 0.8333333333333334 and Train Score 0.9 , rs 3 , k 2
Test Score 0.8333333333333334 and Train Score 0.9 , rs 3 , k 3
Test Score 0.8333333333333334 and Train Score 0.9 , rs 3 , k 4
Test Score 0.8333333333333334 and Train Score 0.8 , rs 3 , k 5
Test Score 0.8333333333333334 and Train Score 0.85 , rs 3 , k 6
Test Score 0.833

In [11]:
# Test Score 0.8333333333333334 and Train Score 0.8 , rs 2 , k 10
x_train,x_test,y_train,y_test = train_test_split(features,label,test_size=0.2,random_state=1)

model = KNeighborsClassifier(n_neighbors=1)

model.fit(x_train,y_train)

trainScore = model.score(x_train,y_train)
testScore = model.score(x_test,y_test)

if testScore >= 0.8:
    print("Model Approved")
else :
    print(f"Model need to imporve {testScore}")

Model Approved


In [12]:
from sklearn.metrics import confusion_matrix

confusion_matrix(label,model.predict(features))

array([[15,  0],
       [ 0, 11]])

In [13]:
model.predict(features) # Predicted Label

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1])

In [14]:
label.ravel() # Actual label

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1])

In [15]:
from sklearn.metrics import classification_report

print(classification_report(label,model.predict(features)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        11

    accuracy                           1.00        26
   macro avg       1.00      1.00      1.00        26
weighted avg       1.00      1.00      1.00        26



In [18]:
CL = 0.8

from sklearn.metrics import f1_score

f1ScoreFromClassificationReport = f1_score(label,model.predict(features),average='macro')
print(f1ScoreFromClassificationReport)
if f1ScoreFromClassificationReport >= CL:
    print("Model Approved")
else:
    print("Improve Model")

1.0
Model Approved
