In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('50_Startups.csv')

In [3]:
data.head()

,R&D Spend,Administration,Marketing Spend,State,Profit
0,165349.20,136897.80,471784.10,New York,192261.83
1,162597.70,151377.59,443898.53,California,191792.06
2,153441.51,101145.55,407934.54,Florida,191050.39
3,144372.41,118671.85,383199.62,New York,182901.99
4,142107.34,91391.77,366168.42,Florida,166187.94


In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [5]:
features = data.iloc[:,[0,1,2,3]].values
label = data.iloc[:,4].values

In [6]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
oheState = OneHotEncoder(sparse_output=True)

dummyState = oheState.fit_transform(features[:,3].reshape(-1,1)).toarray()

In [11]:
dummyState

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0

In [12]:
final_features = np.concatenate((dummyState,features[:,[0,1,2]]),axis=1)

In [13]:
final_features

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

In [16]:
for i in range(1,301):
    for depth in range(3,11):
        x_train,x_test,y_train,y_test = train_test_split(final_features,label,test_size=0.2,random_state=i)
        
        model = RandomForestRegressor(
            n_estimators=5,
            max_depth=depth,
            random_state=2
        )
        
        model.fit(x_train,y_train)
        
        trainScore = model.score(x_train,y_train)
        testScore = model.score(x_test,y_test)
        
        if testScore>trainScore and testScore >=0.9:
            print(f"Test {testScore} | Train {trainScore} and rs {i} | depth {depth}")
        

Test 0.9579400372866264 | Train 0.9521175702589892 and rs 51 | depth 3
Test 0.96149256460898 | Train 0.9537113213257995 and rs 119 | depth 3
Test 0.9694324062169338 | Train 0.9610723949912325 and rs 119 | depth 4
Test 0.9720153964192707 | Train 0.9614975892931061 and rs 119 | depth 5
Test 0.9740242156097941 | Train 0.9639092952311936 and rs 119 | depth 6
Test 0.9733460772177368 | Train 0.962658840386073 and rs 119 | depth 7
Test 0.9730512848916928 | Train 0.9627332519645545 and rs 119 | depth 8
Test 0.9730512848916928 | Train 0.9627332519645545 and rs 119 | depth 9
Test 0.9730512848916928 | Train 0.9627332519645545 and rs 119 | depth 10
Test 0.9490407940274445 | Train 0.9410737710839897 and rs 128 | depth 3
Test 0.9477242915031288 | Train 0.9406180731688222 and rs 128 | depth 4
Test 0.9505817904753446 | Train 0.9385171224550379 and rs 128 | depth 5
Test 0.9508551194752124 | Train 0.9423719439605418 and rs 128 | depth 6
Test 0.9532446304392698 | Train 0.9418276632937647 and rs 128 | dep

In [17]:
# Test 0.9818264162381104 | Train 0.9773719985661841 and rs 158 | depth 5
x_train,x_test,y_train,y_test = train_test_split(final_features,label,test_size=0.2,random_state=158)
model = RandomForestRegressor(
    n_estimators=5,
    max_depth=5,
    random_state=2
)

model.fit(x_train,y_train)

,n_estimators,5
,criterion,'squared_error'
,max_depth,5
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,1.0
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [18]:
data.head()

,R&D Spend,Administration,Marketing Spend,State,Profit
0,165349.20,136897.80,471784.10,New York,192261.83
1,162597.70,151377.59,443898.53,California,191792.06
2,153441.51,101145.55,407934.54,Florida,191050.39
3,144372.41,118671.85,383199.62,New York,182901.99
4,142107.34,91391.77,366168.42,Florida,166187.94


In [ ]:
state = oheState.transform(np.array([['California']]))
state = state.toarray()

array([[1., 0., 0.]])

In [24]:
predict = model.predict(np.array([[1,0,0,20000,20000,20000]]))
predict

array([72382.90466667])